### ISSUE TITLE
create .gitattributes.md template file

### ISSUE THREAD

**Issue by arhimede** [dotkernel/.github#4]
and add it to frontend, admin and api repos

**Comment by bidi47** [comment]
@alexmerlin, i recommend adding these lines, though i'm unsure about the export-ignore items (borrowed from Laminas)

```text
* text=auto
*.png binary
*.md diff=markdown
/.github/ export-ignore
/.laminas-ci/ export-ignore
/.gitignore export-ignore
/phpcs.xml export-ignore
/psalm.xml export-ignore
/psalm-baseline.xml export-ignore
```

**Comment by alexmerlin** [comment]
> @alexmerlin, i recommend adding these lines, though i'm unsure about the export-ignore items (borrowed from Laminas)
> 
> * text=auto

Not sure if `text=auto` is the best approach here.
We need to make sure that we always use lf, regardless the developer's OS.
So maybe `* text eol=lf` would be the better option, because it forces `LF` on all platforms.

> *.png binary

We might include some common image formats as well, like:

```
*.jpg binary
*.jpeg binary
*.svg binary
```

> *.md diff=markdown

Why does Laminas `export-ignore` the below files?

> /.github/ export-ignore
> /.laminas-ci/ export-ignore
> /.gitignore export-ignore
> /phpcs.xml export-ignore

If the rest of the XML files are already here, we should also add:

```
/phpunit.xml export-ignore
```

> /psalm.xml export-ignore
> /psalm-baseline.xml export-ignore

**Comment by bidi47** [comment]
the list below has your updates
the open items that remains is should we ignore anything for the export?

```text
* text eol=lf
*.png binary
*.jpg binary
*.jpeg binary
*.svg binary
*.md diff=markdown
```

**Comment by alexmerlin** [comment]
We can keep above ignore list.
